name: Go tests
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: [v*]

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest
        go-version:
          - 1.19.x
          - 1.22.x
    runs-on: ${{ matrix.os }}
    steps:
      - name: Configure git in Windows.
        run: |
          git config --global core.autocrlf input
        if: ${{ matrix.os == 'windows-latest' }}

      - name: Select changeset to test.
        id: changeset
        uses: actions/github-script@v7
        with:
          script: |
            const outputVarName = 'ref'
            if (gihub.event_name === 'pull_request') {
              console.log("Running in pull request");
              core.setOutput(outputVarName, github.event.pull_request.head.sha);
            } else {
              console.log("Running in branch or tag");
              core.setOutput(outputVarName, github.sha);
            }

      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ steps.event.changeset.ref }}
        if: github.event_name == 'pull_request'

      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: ${{ github.sha }}
        if: github.event_name != 'pull_request'

      - name: Setup Go ${{ matrix.go-version }}.
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Static checks with Go vet.
        run: go vet ./...

      - name: Static checks with Staticcheck.
        run: go run honnef.co/go/tools/cmd/staticcheck ./...

      - name: Test with the Go CLI.
        run: go test -v ./...

      - name: Check pending updates.
        run: |
          go run golang.org/x/tools/cmd/goimports -local github.com/elastic/go-resource/ -w .
          go mod tidy
          git update-index --really-refresh
          git diff-index --quiet HEAD
